#8 Create a Footer Component
Musacoli/afl-ug-frontend pull request #28
Opened 2019-05-01 02:17 UTC by Musacoli

[Closes #8]

**What does this PR do?**
Creates a new Footer component which will be used on all sections of the website.

**Description of Issue to be completed?**
A user is able to view a footer section on each page of the website that they load. This same footer can be used for navigation.

**How should this be manually tested?**
- Clone the following repository ``https://github.com/andela-football-league/afl-ug-frontend.git``
- Checkout the following branch ``ft-create-footer-component``
- Run `yarn install` to install all necessary dependencies.
- Run `yarn start` to run the server locally.
- Open `http://localhost:3000/` in your browser and view it.

**Any background context you want to provide?**
`None`

**What are the relevant GitHub issues?**

[AFL-#8](https://github.com/Musacoli/afl-ug-frontend/issues/8*)

**Screenshots (if appropriate)**
`Working on them`

**Questions:**
`None`

2019-05-02 10:05 UTC, dennisja requested changes

2019-05-02 10:05 UTC, dennisja commented on src/assets/styles/commons/Footer.scss
> +//.right-footer {
Remove uncommented code.
Its a sign that you don't need it

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Header.js
> +						<button type="button" className="reg">
Instead of conditionally switching between the buttons. Just conditionally change its text.
```jsx
<button type="button" className="reg">
	{loggedIn?'LOG OUT':'REGISTER'}
</button
```

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Header.js
> +						<button type="button" className="log">
Instead of conditionally switching between the buttons. Just conditionally change its text.
```jsx
<button type="button" className="log">
	{loggedIn?Profile':'Login'}
</button
```

I see you are doing the same stuff on `LOG OUT` and `REGISTER` button. This can be made a reusable component

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Header.js
>  const Header = ({ loggedIn, pageTitle }) => (
I don't know what the team prefers but this at times turns out to be bad especially if a component takes many props. I personally prefer
```jsx
const Header = (props)=>{
   const {loggedIn, pageTitle} = props
}
```

Over:
```jsx
const Header = ({loggedIn, pageTitle})=>{
}
```
The first one turns out to be more readable especially when you want to add on an extra argument for example in the case of forwarding refs

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Footer.js
> +				<input defaultValue="Email" />
Inputs should have labels associated to them either using the `label` tag or `aria-label` or `aria-labelledby` attributes

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Footer.js
> +	<div className="footer-container">
Use `footer` tag or give the div a role of `contentinfo` for assistive technologies to know. that this is a footer. See [Here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Contentinfo_role#Description)

2019-05-02 10:05 UTC, dennisja commented on package.json
> +		"semantic-ui-react": "^0.86.0"
Why are we having both `semantic-ui-react` and `@material-ui/core`?
Are we even using them any where?

2019-05-02 10:05 UTC, dennisja commented on src/components/commons/Footer.js
> +			<div>Standings</div>
Are these links or? 
Are our users going to interact with them?
If users will interact with them, add them to the tab order by either add a 'tabIndex` prop to the `div` or using a semantic HTML element that is by default in the tab order like a button or an anchor tag

2019-05-02 10:05 UTC, dennisja commented on src/assets/styles/commons/Footer.scss
> +	width: 1920px;
We are using a lot of absolute CSS units, Do we have any dream of making the site responsive?

2019-05-02 10:09 UTC, dennisja requested changes

2019-05-02 10:09 UTC, dennisja commented on src/components/commons/Footer.js
> +			<div>
Would be better to wrap this in the header tag instead of a plain `div`

2019-05-02 10:12 UTC, dennisja requested changes

2019-05-02 10:12 UTC, dennisja commented on src/components/commons/Footer.js
> +				<input defaultValue="Email" />
Use `placeholder` instead of `defaultValue`

2019-05-02 10:15 UTC, dennisja commented
We are using a lot of absolute units in CSS. The site doesn't look good at all on a 13screen inch. The user experience is bad as a person has to scroll vertically and horizontally. We can do better by using relative units for the site to look at least better on `13 inch` Macbook

2019-05-08 03:07 UTC, Musacoli commented on package.json
> +		"semantic-ui-react": "^0.86.0"
Hadn't yet decided which is to be used but have rectified that.

2019-05-08 11:33 UTC, john555 commented on src/assets/styles/Default.scss
> +	min-height: 200vh;
Why should the min-height be twice the viewport height?

2019-05-08 11:34 UTC, john555 commented on src/components/commons/Header.js
> +		<header className="header-container">
What indentation are you using?

2019-05-08 11:35 UTC, john555 commented on src/containers/DefaultLayout.js
> +	const { children, pageTitle } = props;
You could destructure from the arguments. 
```
const DefaultLayout = ({ children, pageTitle }) => {
  ...
```

2019-05-08 11:38 UTC, john555 commented on src/containers/DefaultLayout.js
> +	pageTitle: '',
Instead of passing an empty string as a prop, avoid rendering the <Header /> component if the `pageTitle` does not exist.

2019-05-08 11:39 UTC, john555 commented on src/containers/Homepage.js
> +export default connect()(Homepage);
There is no need to "connect" the component here since you are neither mapping state nor dispatch to props.

2019-05-08 11:41 UTC, john555 commented on src/index.js
> +							name={route.name}
This indentation really needs fixing - a tab width of 2 spaces it very common for js.

2019-05-08 11:49 UTC, john555 commented on src/assets/styles/commons/Footer.scss
> +$screen-large: 'screen and (min-width: 1920px) and (max-height: 1080px)';
This media query condition is very limiting. Do not consider height for media queries.

2019-05-08 12:08 UTC, dennisja requested changes

2019-05-08 12:08 UTC, dennisja commented on src/containers/DefaultLayout.js
> +	children: PropTypes.shape({}).isRequired,
Change this to `PropTypes.node.iSRequired`.

2019-05-08 12:08 UTC, dennisja commented on src/containers/DefaultLayout.js
> +	const { children, pageTitle } = props;
This usually results into unreadable function definitions if props become many. And if you ever want to do something like ref forwarding it becomes even worse and confusing. For example:-
With destructure in arguments
```jsx
export const DefaultLayout = React.forwardRef(({children, x, y, z}, ref)=>{
  //......
})
```
With destructure inside a function:
```jsx
export const DefaultLayout = React.forwardRef((props, ref)=>{
  const {children, x, y, z} = props
  //......
})
```

It might as well not be readable when doing nested destructuring
Destructuring in arguments
```jsx
export const DefaultLayout = ({
  children,
  pageTitle,
  person: {
    age,
    name,
    profile: { friends },
  },
}) => {
  //......
};
```
Destructuring inside function
```jsx
export const DefaultLayout = (props) => {
  const {
    children,
    pageTitle,
    person: {
      age,
      name,
      profile: { friends },
    },
  } = props;
  //......
};
```
If we ever introduce a type checker. Destructuring props inside a function looks much more cleaner than in the arguments. The type are easier to spot when destructuring is done inside a function.
Destructuring props
```jsx
type Props = {
  children: ReactNode,
  pageTitle: string,
  person: { age: number, name: string, profile: { friends: Friends[] } },
};

export const DefaultLayout = ({
  children,
  pageTitle,
  person: {
    age,
    name,
    profile: { friends },
  },
}: Props) => {
  //......
};
```

Destructuring inside function
```jsx
type Props = {
  children: ReactNode,
  pageTitle: string,
  person: { age: number, name: string, profile: { friends: Friends[] } },
};

export const DefaultLayout = (props: Props) => {
  const {
    children,
    pageTitle,
    person: {
      age,
      name,
      profile: { friends },
    },
  } = props;
  //......
};
```
However both approaches have no problems. I think we should just come up with what other members prefer and stick with that to ensure consistency in the codebase cuz one of the things that contribute to code readability is consistency. But on my side I would go with what @Musacoli did

2019-05-08 12:15 UTC, dennisja requested changes

2019-05-08 12:15 UTC, dennisja commented on src/views/Home.js
> +const Home = ({ ...props }) => (
This is wrong. Change it to 
```jsx
const Home = (props) => (
	<DefaultLayout {...props}>
		<Homepage {...props} />
	</DefaultLayout>
);
```
But its as well dangerous, I would advise you to only pass props necessary to each component to avoid re rendering a component if it shouldn't rerender for example
```jsx
const Home = (props) => {
const { color, otherLayoutProp, ...homePageProps}
return (
	<DefaultLayout color={color}, otherLayoutProp={otherLayoutProp}>
		<Homepage {...homePageProps} />
	</DefaultLayout>
);
}

```

2019-05-08 12:29 UTC, Musacoli commented on src/containers/Homepage.js
> +export default connect()(Homepage);
At the moment am not yet mapping but when that component is complete there will be need for mapping.

2019-05-08 12:31 UTC, Musacoli commented on src/index.js
> +							name={route.name}
Noted have made this correction

2019-05-08 12:31 UTC, Musacoli commented on src/assets/styles/Default.scss
> +	min-height: 200vh;
This was an oversight. Let me rectify it.

2019-05-08 12:34 UTC, Musacoli commented on src/components/commons/Header.js
> +		<header className="header-container">
Was using Tab-size 4,
But have changed it to 2

2019-05-08 12:51 UTC, Musacoli commented on src/views/Home.js
> +const Home = ({ ...props }) => (
At the moment the definite prop names have not been defined for that component hence why am just passing the props alone.
But it indeed would be better to pass the required props only.

Noted

2019-05-08 14:48 UTC, Musacoli commented on src/containers/DefaultLayout.js
> +	const { children, pageTitle } = props;
The Team decided that we use this ```const TestFunction = (props) => {
  const { children, prop2, prop3 } = props;
}```.

So I guess we shall stick to that at the moment.

2019-05-09 19:12 UTC, dennisja approved these changes

2019-05-09 19:31 UTC, merged